# Generated by Django 5.0.1 on 2024-02-09 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0006_remove_jobseeker_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_industry', to='backend.industry')),
                ('prefferd_job', models.ManyToManyField(related_name='seeker_prefferd_job', to='backend.prefferedjob')),
                ('skills', models.ManyToManyField(related_name='seeker_skills', to='backend.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_details', to='backend.jobseeker')),
            ],
        ),
    ]
