# Generated by Django 5.0.1 on 2024-02-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
    ]
