# Generated by Django 5.0.1 on 2024-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_alter_jobseekerdetails_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerdetails',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='seekerProfilePic'),
        ),
    ]
