# Generated by Django 5.0.1 on 2024-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_jobseekerdetails_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
