# Generated by Django 5.0.1 on 2024-08-26 10:11

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_jobseekerdetails_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='profilePic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[105, 80], upload_to='seekerProfilePic'),
        ),
    ]
