# Generated by Django 5.0.1 on 2024-06-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_events_thumbnail'),
        ('quiz', '0003_alter_quizanswers_quiz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquiz',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_quiz', to='backend.recruiter'),
        ),
    ]
