# Generated by Django 5.0.1 on 2024-06-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_events_thumbnail'),
        ('quiz', '0004_jobquiz_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquiz',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_quiz', to='backend.recruiter'),
            preserve_default=False,
        ),
    ]
