# Generated by Django 5.0.1 on 2024-06-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_jobquiz_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquiz',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
