# Generated by Django 5.0.1 on 2024-06-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_jobquiz_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobquiz',
            name='quiz_score',
        ),
    ]
