# Generated by Django 5.0.1 on 2024-08-12 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_jobquiz_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquiz',
            name='total_quiz_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
