# Generated by Django 5.0.1 on 2024-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(0, 'Agriculture'), (1, 'IT'), (2, 'Education'), (3, 'Engineering')])),
            ],
        ),
    ]
