# Generated by Django 5.0.1 on 2024-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_educationinfo_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='degree_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
