# Generated by Django 5.0.1 on 2024-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_educationinfo_degree_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefferedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
