# Generated by Django 5.0.1 on 2024-02-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_prefferedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='dob',
        ),
    ]
