# Generated by Django 5.0.1 on 2024-02-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_jobseeker_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterLeadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedLeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.recruiterleaddetails')),
            ],
        ),
    ]
