# Generated by Django 5.0.1 on 2024-02-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_recruiterleaddetails_generatedleadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_seeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedleadstatus',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recuiter_lead', to='backend.recruiterleaddetails'),
        ),
    ]
