# Generated by Django 5.0.1 on 2024-06-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=120)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
