# Generated by Django 5.0.1 on 2024-06-09 06:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_pagemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[20, 20], upload_to='icons'),
        ),
    ]
