# Generated by Django 5.0.1 on 2024-06-10 06:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[254, 254], upload_to='events-image'),
        ),
    ]
