# Generated by Django 5.0.1 on 2024-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_events_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterleaddetails',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
