# Generated by Django 5.0.1 on 2024-08-18 07:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_recruiterleaddetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterleaddetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
