# Generated by Django 5.0.1 on 2024-08-12 06:28

import blog.models
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(required=False)), ('image', blog.models.ImageChooserBlock(required=False))], blank=True),
        ),
    ]
