# Generated by Django 5.0.1 on 2024-02-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_educationinfo_skills'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_years_of_experience', models.PositiveSmallIntegerField(choices=[(0, 'not important'), (1, 'less than three'), (2, 'between three and six'), (3, 'more than six')])),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('salary', models.PositiveIntegerField()),
                ('number_of_vacancy', models.PositiveSmallIntegerField()),
                ('work_location_type', models.PositiveSmallIntegerField(choices=[(0, 'Remote'), (1, 'Onsite'), (2, 'Hybrid')])),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Intern'), (1, 'Freshers'), (2, 'Experienced')])),
                ('apply_before', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='backend.recruiter')),
                ('education_info', models.ManyToManyField(related_name='job_education_info', to='backend.educationinfo')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_industry', to='backend.industry')),
                ('required_skills', models.ManyToManyField(related_name='jobs_skills', to='backend.skills')),
            ],
        ),
    ]
