# Generated by Django 5.0.1 on 2024-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_prefferedjob'),
        ('recruiter', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ManyToManyField(blank=True, related_name='preffered_job', to='backend.prefferedjob'),
        ),
    ]
