# Generated by Django 5.0.1 on 2024-02-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_jobseeker_dob'),
        ('recruiter', '0003_job_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_status', models.PositiveSmallIntegerField(choices=[(1, 'seen'), (0, 'not seen')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'waiting'), (1, 'denied')], default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_request', to='recruiter.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_seeker_request', to='backend.jobseeker')),
            ],
        ),
    ]
