# Generated by Django 5.0.1 on 2024-02-26 11:35

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_recruiterdetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
