# Generated by Django 5.0.1 on 2024-02-28 08:03

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_alter_recruiterdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
