# Generated by Django 5.0.1 on 2024-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_job_approved',
            field=models.BooleanField(default=False),
        ),
    ]
