# Generated by Django 5.0.1 on 2024-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_customuser_is_seeker_and_more'),
        ('recruiter', '0009_alter_recruiterdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.ManyToManyField(related_name='preffered_job', to='backend.prefferedjob'),
        ),
    ]
