# Generated by Django 5.0.1 on 2024-04-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_job_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterdetails',
            name='company_size',
        ),
        migrations.AddField(
            model_name='recruiterdetails',
            name='company_max_size',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recruiterdetails',
            name='company_min_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
