# Generated by Django 5.0.1 on 2024-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_remove_job_salary_job_max_salary_job_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
