# Generated by Django 5.0.1 on 2024-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_alter_recruiterdetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
