# Generated by Django 5.0.1 on 2024-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_alter_recruiterdetails_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_years_of_experience',
            field=models.PositiveSmallIntegerField(choices=[(0, '0-1'), (1, '1-3'), (2, 'between three and six'), (3, 'more than six')]),
        ),
    ]
