# Generated by Django 5.0.1 on 2024-06-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizanswers_quiz_question_and_more'),
        ('recruiter', '0018_jobrequest_applied_on_alter_jobrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quiz',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_for_job', to='quiz.jobquiz'),
            preserve_default=False,
        ),
    ]
