# Generated by Django 5.0.1 on 2024-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0020_alter_job_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quiz_sorce',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
