# Generated by Django 5.0.1 on 2024-06-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0021_jobrequest_quiz_sorce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='quiz_sorce',
            new_name='quiz_score',
        ),
    ]
