# Generated by Django 5.0.1 on 2024-06-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0022_rename_quiz_sorce_jobrequest_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='quiz_score',
        ),
    ]
