# Generated by Django 5.0.1 on 2024-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0023_remove_jobrequest_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
