# Generated by Django 5.0.1 on 2024-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0025_remove_jobrequest_quiz_score_jobrequest_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='quiz',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
