# Generated by Django 5.0.1 on 2024-07-02 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0027_job_job_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
