# Generated by Django 5.0.1 on 2024-07-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0029_job_has_expried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='has_expried',
        ),
    ]
