# Generated by Django 5.0.1 on 2024-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0030_remove_job_has_expried'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quiz_completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
