# Generated by Django 5.0.1 on 2024-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0031_jobrequest_quiz_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='quiz_completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
