# Generated by Django 5.0.1 on 2024-08-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0032_alter_jobrequest_quiz_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
