# Generated by Django 5.0.1 on 2024-08-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0033_alter_recruiterdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='phone',
            field=models.PositiveBigIntegerField(default=123),
            preserve_default=False,
        ),
    ]
