# Generated by Django 5.0.1 on 2024-08-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0034_alter_recruiterdetails_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_unique_id',
        ),
    ]
