# Generated by Django 5.0.1 on 2024-08-18 08:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0035_remove_job_job_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='recruiterdetails',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
